const $=s=>document.querySelector(s), money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)), store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let fbReady=false, db=null, auth=null, storage=null, edit=null, products=[], orders=[];
try{if(window.GC_FIREBASE_CONFIG && !String(window.GC_FIREBASE_CONFIG.apiKey).includes('COLE')){firebase.initializeApp(window.GC_FIREBASE_CONFIG);db=firebase.firestore();auth=firebase.auth();storage=firebase.storage();fbReady=true;}}catch(e){console.warn(e)}
function enter(){if($('#adminPass').value==='Gu040310@'){localStorage.setItem('gc_admin','1');show()}else alert('Senha incorreta')}
async function show(){if(localStorage.getItem('gc_admin')==='1'){$('#login').style.display='none';$('#dash').style.display='block';await render()}}
async function fetchData(){ if(fbReady){let ps=await db.collection('products').get(); products=ps.docs.map(d=>({id:d.id,...d.data()})); let os=await db.collection('orders').orderBy('createdAt','desc').get().catch(()=>db.collection('orders').get()); orders=os.docs.map(d=>({id:d.id,...d.data()}));} else {products=load('gc_products',[]); orders=load('gc_orders',[])} }
async function render(){await fetchData();$('#prodCount').textContent=products.length;$('#sales').textContent=orders.length;$('#revenue').textContent=money(orders.reduce((a,x)=>a+Number(x.total||0),0));$('#clients').textContent=new Set(orders.map(x=>x.email)).size;$('#adminProducts').innerHTML=(fbReady?'<p class="ok">Admin online conectado ao Firebase.</p>':'<p class="firebaseWarn">Modo local. Configure o Firebase para admin online.</p>')+products.map(x=>`<div class="mini"><b>${x.name}</b><p>${money(x.price)} • ${x.cat} • ${x.brand}</p><p class="small">Imagem: ${x.image||'sem imagem'}</p><button class="ghost" onclick="editProduct('${x.id}')">Editar</button> <button class="ghost" onclick="delProduct('${x.id}')">Excluir</button></div>`).join('')||'<p>Sem produtos.</p>';$('#adminOrders').innerHTML=orders.map(x=>`<div class="mini"><b>${x.id}</b><p>${x.email} • ${money(x.total)}</p><select onchange="statusOrder('${x.id}',this.value)">${['Aguardando comprovante Pix','Pago','Em preparação','Enviado','Entregue','Cancelado'].map(s=>`<option ${s==x.status?'selected':''}>${s}</option>`).join('')}</select><input placeholder="Código de rastreio" value="${x.tracking||''}" onchange="trackOrder('${x.id}',this.value)"></div>`).join('')||'<p>Sem pedidos ainda.</p>'}
async function uploadImage(id){let f=$('#pfile').files[0]; if(!f||!fbReady)return $('#pimage').value; let ref=storage.ref('produtos/'+id+'-'+f.name); await ref.put(f); return await ref.getDownloadURL();}
async function saveProduct(){let id=edit||String(Date.now()); let img=await uploadImage(id); let obj={id,name:$('#pname').value,brand:$('#pbrand').value||'GC',cat:$('#pcat').value||'Produtos',price:Number($('#pprice').value.replace(',','.'))||0,sizes:['P','M','G','GG'],stock:10,tag:'Novo',desc:$('#pdesc').value,image:img||'assets/produto-kit.svg',updatedAt:Date.now()}; if(fbReady){await db.collection('products').doc(id).set(obj,{merge:true});}else{let p=load('gc_products',[]); p=edit?p.map(x=>String(x.id)==String(edit)?obj:x):[...p,obj]; store('gc_products',p)} edit=null;['pname','pbrand','pcat','pprice','pdesc','pimage'].forEach(i=>$('#'+i).value='');$('#pfile').value='';render()}
function editProduct(id){let x=products.find(p=>String(p.id)==String(id));edit=id;$('#pname').value=x.name||'';$('#pbrand').value=x.brand||'';$('#pcat').value=x.cat||'';$('#pprice').value=x.price||'';$('#pdesc').value=x.desc||'';$('#pimage').value=x.image||''}
async function delProduct(id){if(!confirm('Excluir produto?'))return; if(fbReady)await db.collection('products').doc(id).delete(); else store('gc_products',load('gc_products',[]).filter(x=>String(x.id)!=String(id))); render()}
async function statusOrder(id,v){if(fbReady)await db.collection('orders').doc(id).update({status:v}); else {let o=load('gc_orders',[]);let item=o.find(x=>String(x.id)==String(id)); if(item)item.status=v;store('gc_orders',o)} render()}
async function trackOrder(id,v){if(fbReady)await db.collection('orders').doc(id).update({tracking:v}); else {let o=load('gc_orders',[]);let item=o.find(x=>String(x.id)==String(id)); if(item)item.tracking=v;store('gc_orders',o)}}
show();
