const PIX='ad586de2-610a-4874-bb22-ee6a8cbe68c2', WHATS='5511913034323';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const defaultProducts=[
{id:'1',name:'Jaqueta Tommy Importada',brand:'Tommy',cat:'Jaquetas',price:499.99,sizes:['P','M','G','GG'],stock:3,tag:'Oferta',desc:'Jaqueta premium sob encomenda. No Brasil custa em média R$ 600, aqui sai por R$ 499,99.',image:'assets/produto-jaqueta.svg'},
{id:'2',name:'Camiseta Dri-Fit 21',brand:'Nike',cat:'Camisetas',price:89.90,sizes:['P','M','G'],stock:8,tag:'Mais pedido',desc:'Camiseta leve para usar no corre e no dia a dia.',image:'assets/produto-drifit.svg'},
{id:'3',name:'Short Tactel',brand:'GC',cat:'Shorts',price:69.90,sizes:['P','M','G','GG'],stock:10,tag:'Corre',desc:'Short confortável, estilo rua.',image:'assets/produto-short.svg'},
{id:'4',name:'Kit Camiseta + Short',brand:'GC',cat:'Kits',price:139.90,sizes:['P','M','G'],stock:5,tag:'Combo',desc:'Kit completo para sair trajado.',image:'assets/produto-kit.svg'},
{id:'5',name:'Boné Lacoste Branco',brand:'Lacoste',cat:'Acessórios',price:119.90,sizes:['Único'],stock:4,tag:'Acessório',desc:'Boné branco para compor o kit.',image:'assets/produto-bone.svg'}];
let fbReady=false, db=null, auth=null, storageRef=null;
try{ if(window.GC_FIREBASE_CONFIG && !String(window.GC_FIREBASE_CONFIG.apiKey).includes('COLE')){ firebase.initializeApp(window.GC_FIREBASE_CONFIG); db=firebase.firestore(); auth=firebase.auth(); storageRef=firebase.storage(); fbReady=true; }}catch(e){console.warn(e)}
let products=load('gc_products',defaultProducts), cart=load('gc_cart',[]), user=load('gc_user',null), orders=load('gc_orders',[]), wish=load('gc_wish',[]), recent=load('gc_recent',[]), ship=0, discount=0;
async function syncProducts(){ if(!fbReady){store('gc_products',products);return} let snap=await db.collection('products').get(); if(snap.empty){for(const p of defaultProducts) await db.collection('products').doc(String(p.id)).set(p); products=defaultProducts}else products=snap.docs.map(d=>({id:d.id,...d.data()})); store('gc_products',products); initFilters(); renderProducts();}
async function syncOrders(){ if(!fbReady||!user) return; let snap=await db.collection('orders').where('email','==',user.email).get(); orders=snap.docs.map(d=>({id:d.id,...d.data()})); store('gc_orders',orders); account(); }
function initFilters(){['cat','brand','size'].forEach(id=>$('#'+id).innerHTML='<option value="">'+(id=='cat'?'Categoria':id=='brand'?'Marca':'Tamanho')+'</option>'); [...new Set(products.map(p=>p.cat).filter(Boolean))].forEach(v=>$('#cat').innerHTML+=`<option>${v}</option>`); [...new Set(products.map(p=>p.brand).filter(Boolean))].forEach(v=>$('#brand').innerHTML+=`<option>${v}</option>`); ['P','M','G','GG','Único'].forEach(v=>$('#size').innerHTML+=`<option>${v}</option>`)}
function renderProducts(){let q=$('#search').value.toLowerCase(), c=$('#cat').value, s=$('#size').value, b=$('#brand').value, arr=products.filter(p=>(!q||p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q))&&(!c||p.cat==c)&&(!b||p.brand==b)&&(!s||(p.sizes||[]).includes(s))); if($('#sort').value=='low')arr.sort((a,b)=>a.price-b.price); if($('#sort').value=='high')arr.sort((a,b)=>b.price-a.price); $('#products').innerHTML=arr.map(p=>`<article class="card"><div class="pic"><img src="${p.image||'assets/produto-kit.svg'}" alt="${p.name}"><span class="tag">${p.tag||'Novo'}</span><button class="fav ghost" onclick="toggleWish('${p.id}')">${wish.includes(String(p.id))?'♥':'♡'}</button></div><div class="info"><p class="muted">${p.cat} • ${p.brand}</p><div class="row"><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div><p class="muted">${p.desc}</p><p>⭐ 4,8 • Estoque: ${p.stock||0}</p><div class="actions"><button class="ghost" onclick="showProduct('${p.id}')">Ver</button><button class="btn" onclick="addCart('${p.id}')">Adicionar</button></div></div></article>`).join('')||'<p>Nenhum produto encontrado.</p>'; renderMini()}
function addCart(id){let p=products.find(x=>String(x.id)==String(id)), item=cart.find(x=>String(x.id)==String(id)); if(!p)return; item?item.q++:cart.push({id:String(id),q:1,size:(p.sizes||['Único'])[0]}); store('gc_cart',cart); renderCart(); alert('Produto adicionado ao carrinho!')}
function renderCart(){ $('#cartCount').textContent=cart.reduce((a,i)=>a+i.q,0); let sub=0; $('#cartItems').innerHTML=cart.map(i=>{let p=products.find(x=>String(x.id)==String(i.id)); if(!p)return ''; sub+=Number(p.price)*i.q; return `<div class="cartItem"><div><b>${p.name}</b><p>${money(p.price)} • Qtd ${i.q}</p><select onchange="setSize('${i.id}',this.value)">${(p.sizes||['Único']).map(z=>`<option ${z==i.size?'selected':''}>${z}</option>`).join('')}</select></div><button class="ghost" onclick="removeCart('${i.id}')">Remover</button></div>`}).join('')||'<p>Carrinho vazio.</p>'; let total=Math.max(0,sub+ship-discount); $('#totals').innerHTML=`<p>Subtotal: ${money(sub)}</p><p>Frete: ${money(ship)}</p><p>Desconto: -${money(discount)}</p><h3>Total: ${money(total)}</h3><p class="muted">Pix manual: ${PIX}</p>`; store('gc_cart',cart)}
function setSize(id,v){cart.find(i=>String(i.id)==String(id)).size=v; renderCart()} function removeCart(id){cart=cart.filter(i=>String(i.id)!=String(id)); renderCart()} function toggleWish(id){id=String(id);wish=wish.includes(id)?wish.filter(x=>x!=id):[...wish,id];store('gc_wish',wish);renderProducts()} 
function showProduct(id){let p=products.find(x=>String(x.id)==String(id)); recent=[String(id),...recent.filter(x=>x!=String(id))].slice(0,5); store('gc_recent',recent); $('#modal').innerHTML=`<div class="modalBox"><button class="x" onclick="closeModal()">×</button><h2>${p.name}</h2><img src="${p.image}" style="width:100%;max-height:280px;object-fit:cover;border-radius:22px"><p>${p.desc}</p><p><b>${money(p.price)}</b></p><p>Tamanhos: ${(p.sizes||[]).join(', ')}</p><textarea id="newReview" placeholder="Escreva uma avaliação"></textarea><button class="ghost full" onclick="saveReview('${id}')">Enviar avaliação</button><button class="btn full" onclick="addCart('${id}');closeModal()">Adicionar ao carrinho</button></div>`; $('#modal').classList.add('open'); renderMini()}
function closeModal(){$('#modal').classList.remove('open')} function renderMini(){const mini=id=>{let p=products.find(x=>String(x.id)==String(id));return p?`<div class="mini"><b>${p.name}</b><p>${money(p.price)}</p></div>`:''}; $('#recent').innerHTML=recent.map(mini).join('')||'<p class="muted">Nenhum produto visto ainda.</p>'; $('#wishlist').innerHTML=wish.map(mini).join('')||'<p class="muted">Nenhum favorito ainda.</p>'}
function account(){ if(user){$('#accountBox').innerHTML=`<p>Logado como <b>${user.name}</b></p>${fbReady?'<p class="ok">Conta online conectada ao Firebase.</p>':'<p class="firebaseWarn">Modo local: configure o Firebase para login real.</p>'}<h3>Histórico de pedidos</h3>${orders.filter(o=>o.email==user.email).map(o=>`<div class="mini"><b>${o.id}</b><p>${o.status} • ${money(o.total)}</p></div>`).join('')||'<p>Sem pedidos.</p>'}<button class="ghost full" onclick="logout()">Sair</button>`}else{$('#accountBox').innerHTML=`${fbReady?'':'<p class="firebaseWarn">Firebase ainda sem configuração. Login ficará local até colar as chaves.</p>'}<input id="name" placeholder="Nome"><input id="email" placeholder="E-mail"><input id="pass" type="password" placeholder="Senha"><button class="btn full" onclick="login()">Entrar / Cadastrar</button><button class="ghost full" onclick="googleLogin()">Entrar com Google</button><button class="ghost full" onclick="recoverPass()">Recuperar senha</button>`}}
async function login(){let email=$('#email').value||'cliente@email.com', pass=$('#pass').value||'123456', name=$('#name').value||'Cliente'; if(fbReady){try{let cred; try{cred=await auth.signInWithEmailAndPassword(email,pass)}catch(e){cred=await auth.createUserWithEmailAndPassword(email,pass); await cred.user.updateProfile({displayName:name})} user={name:cred.user.displayName||name,email:cred.user.email,uid:cred.user.uid}; await db.collection('users').doc(user.uid).set(user,{merge:true});}catch(e){return alert('Erro no login: '+e.message)}} else user={name,email}; store('gc_user',user); await syncOrders(); account()}
async function googleLogin(){ if(!fbReady){user={name:'Cliente Google',email:'google@cliente.com'};store('gc_user',user);account();return alert('Google real precisa do Firebase configurado.')} try{let provider=new firebase.auth.GoogleAuthProvider(), cred=await auth.signInWithPopup(provider); user={name:cred.user.displayName,email:cred.user.email,uid:cred.user.uid}; await db.collection('users').doc(user.uid).set(user,{merge:true}); store('gc_user',user); await syncOrders(); account()}catch(e){alert('Erro no Google: '+e.message)}}
async function logout(){ if(fbReady) await auth.signOut(); user=null; orders=[]; store('gc_user',null); account()}
async function recoverPass(){let email=$('#email')?.value; if(fbReady&&email){await auth.sendPasswordResetEmail(email); alert('E-mail de recuperação enviado.')} else alert('Digite seu e-mail. Com Firebase configurado, o link será enviado de verdade.')}
async function checkout(){if(!cart.length)return alert('Carrinho vazio.'); if(!user){$('#accountPanel').classList.add('open'); return alert('Faça login antes de finalizar.')} let sub=cart.reduce((a,i)=>a+Number(products.find(p=>String(p.id)==String(i.id)).price)*i.q,0), total=Math.max(0,sub+ship-discount), id='GC'+Date.now().toString().slice(-6); let order={id,email:user.email,items:cart,total,status:'Aguardando comprovante Pix',tracking:'',date:new Date().toLocaleString('pt-BR'),createdAt:Date.now()}; if(fbReady) await db.collection('orders').doc(id).set(order); orders.push(order); store('gc_orders',orders); let msg=`Pedido ${id}%0ATotal: ${money(total)}%0APix: ${PIX}%0ACliente: ${user.name}%0AEnviar comprovante do Pix aqui.`; cart=[]; discount=0; ship=0; renderCart(); window.open(`https://wa.me/${WHATS}?text=${msg}`,'_blank'); alert('Pedido criado! Envie o comprovante no WhatsApp.')}
async function saveReview(id){let text=$('#newReview').value.trim(); if(!text)return; if(fbReady) await db.collection('reviews').add({productId:id,text,user:user?.name||'Cliente',stars:5,date:Date.now()}); alert('Avaliação enviada!')}
function renderReviews(){let rs=['Chegou certinho, atendimento rápido.','As peças são muito bonitas pessoalmente.','Gostei do preço e do suporte no WhatsApp.']; $('#reviews').innerHTML=rs.map((r,i)=>`<div class="review"><h3>⭐⭐⭐⭐⭐</h3><p>${r}</p><b>Cliente ${i+1}</b></div>`).join('')}
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.panel').classList.remove('open')); $('#openCart').onclick=()=>$('#cartPanel').classList.add('open'); $('#openAccount').onclick=()=>{$('#accountPanel').classList.add('open');account()}; $('#checkout').onclick=checkout; $('#applyCoupon').onclick=()=>{let c=$('#coupon').value.toUpperCase();discount=c=='GC10'?20:c=='FRETE15'?15:0;renderCart()}; $('#calcShip').onclick=()=>{let cep=$('#cep').value.replace(/\D/g,''); ship=cep.length==8?24.90:0; renderCart(); alert(ship?'Frete estimado calculado.':'Digite um CEP válido.')}; $('#trackBtn').onclick=async()=>{let id=$('#trackInput').value.trim().toUpperCase(), o=orders.find(x=>x.id==id); if(fbReady&&!o){let d=await db.collection('orders').doc(id).get(); if(d.exists)o={id:d.id,...d.data()}} $('#trackResult').innerHTML=o?`<h3>${o.status}</h3><p>Código de rastreio: ${o.tracking||'Ainda não informado'}</p>`:'Pedido não encontrado.'}; $('#saveEmail').onclick=async()=>{let email=$('#emailPromo').value;if(fbReady)await db.collection('newsletter').add({email,date:Date.now()});alert('E-mail cadastrado para promoções!')}; ['search','cat','size','brand','sort'].forEach(id=>$('#'+id).oninput=renderProducts); initFilters(); renderProducts(); renderCart(); renderReviews(); account(); syncProducts(); if(fbReady&&auth)auth.onAuthStateChanged(u=>{if(u){user={name:u.displayName||'Cliente',email:u.email,uid:u.uid};store('gc_user',user);syncOrders();}});
